name: Test
on: push
jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run:  sudo apt install lua-check
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Test
        run: LUA_PATH="lua/?/init.lua;lua/?.lua;$(lua -e 'print(package.path)')" make
  macos:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - name: Install Deps
        run:  |
          brew install luarocks
          luarocks install luacheck
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Test
        run: LUA_PATH="lua/?/init.lua;lua/?.lua;$(lua -e 'print(package.path)')" make
