name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - run: ls
      - run: pwd
      - name: test
        run: make
