name: Test
on: push
jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: |
          sudo apt install lua5.1
          export PLUGDIR=/home/runner/.config/nvim/pack/plugins/opt
          mkdir -p $PLUGDIR
          git clone https://github.com/rktjmp/hotpot.nvim "${PLUGDIR}/hotpot"
      - name: Test
        run: LUA_PATH="fnl/?/init.fnl;fnl/?.fnl;$(lua -e 'print(package.path)');$(lua -e 'print(package.path:gsub("lua","fnl"))')" make
  macos:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: |
          brew install lua@5.1
          export PLUGDIR=/Users/runner/.config/nvim/pack/plugins/opt
          mkdir -p $PLUGDIR
          git clone https://github.com/rktjmp/hotpot.nvim "${PLUGDIR}/hotpot"
      - name: Test
        run: LUA_PATH="fnl/?/init.fnl;fnl/?.fnl;$(lua5.1 -e 'print(package.path)');$(lua5.1 -e 'print(package.path:gsub("lua","fnl"))')" make
